-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgY0UB8iznXsoJSv90
RCR8UyjSFCUvcVROc5FNaIiSWuSgCgYIKoZIzj0DAQehRANCAASohj4IoioitCwB
t+PoYOarsjZjUawBHdeQWI7eQvTP9Npti5NK8ps4/ej9GC4j+C1EJstlO3uWGMuV
aVEQ/fMZ
-----END PRIVATE KEY-----